# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 115

Metrics/BlockLength:
  ExcludedMethods: ['resource', 'namespace', 'describe', 'context']

Style/FrozenStringLiteralComment:
  Enabled: false
