# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 115

Metrics/BlockLength:
  ExcludedMethods: ['resource', 'namespace', 'describe', 'context']
