version: 2
jobs:
  build:
    working_directory: ~/kicksite_svc_client
    docker:
      - image: cimg/ruby:2.5.9
        environment:
          RAILS_ENV: test
          KICKSITE_SVC_URL: https://api.kicksite-staging.net
          KICKSITE_AUTH_URL: https://auth.kicksite-staging.net

    steps:
      - checkout

      # Bundle install dependencies
      - run:
          name: Bundle Install
          command: bundle _1.17.3_ install --path=vendor/bundle --jobs 4 --retry 3

      - run:
          name: Run Tests
          command: bundle exec rspec spec

      - run:
          name: Run static code analyzer
          command: |
            gem install rubocop
            rubocop --format html -o tmp/test-results/rubocop/results.html

      - store_artifacts:
          path: ./tmp/test-results

workflows:
  version: 2
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
